// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fsfmrxuhvefaqcxaretw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzZm1yeHVodmVmYXFjeGFyZXR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA5MTQ5NTUsImV4cCI6MjA3NjQ5MDk1NX0.BpsJqGo8fuchOPMGPEYcpnmArlZtX0OqLCfpvHaji_0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
